name: Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build:
    permissions:
      contents: read
    strategy:
      matrix:
        os: [windows-latest, windows-11-arm]
        platform: [x64, x86, ARM64, ARM64EC]
        config: [Debug, Release]
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
    - name: Source checkout
      uses: actions/checkout@main
      with:
        submodules: recursive
    - name: Prepare MSBuild
      uses: microsoft/setup-msbuild@main
    - name: Build
      run: msbuild .\Source\KNSoft.NDK.sln /restore /m /p:Configuration=${{matrix.config}} /p:Platform=${{matrix.platform}} /p:RestorePackagesConfig=true
    - name: Run Unit Test
      if: ${{(matrix.os == 'windows-latest' && (matrix.platform == 'x64' || matrix.platform == 'x86') || matrix.os == 'windows-11-arm')}}
      run: .\Source\OutDir\${{matrix.platform}}\${{matrix.config}}\UnitTest.exe -Run
    - name: Archive outputs
      uses: actions/upload-artifact@main
      with:
        name: KNSoft.NDK-${{matrix.platform}}-${{matrix.config}}-${{github.sha}}
        path: |
          .\Source\OutDir\${{matrix.platform}}\${{matrix.config}}
          .\Source\Include
  Publish:
    if: ${{github.base_ref == '' && startsWith(github.event.head_commit.message, '[VERSION] ')}}
    needs: Build
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
    - name: Set release version
      id: relver
      shell: pwsh
      run: |
        $relver="${{github.event.head_commit.message}}".Substring(10)
        Write-Output "relver=$relver">>$env:GITHUB_OUTPUT
    - name: Source checkout
      uses: actions/checkout@main
      with:
        submodules: recursive
    - name: Prepare MSBuild
      uses: microsoft/setup-msbuild@main
    - name: Build
      run: |
        msbuild .\Source\KNSoft.NDK.sln /restore /m /p:Configuration=Release /p:Platform=x64 /p:RestorePackagesConfig=true
        msbuild .\Source\KNSoft.NDK.sln /restore /m /p:Configuration=Release /p:Platform=x86 /p:RestorePackagesConfig=true
        msbuild .\Source\KNSoft.NDK.sln /restore /m /p:Configuration=Release /p:Platform=ARM64 /p:RestorePackagesConfig=true
        msbuild .\Source\KNSoft.NDK.sln /restore /m /p:Configuration=Release /p:Platform=ARM64EC /p:RestorePackagesConfig=true
    - name: Run Unit Test
      run: |
        .\Source\OutDir\x64\Release\UnitTest.exe -Run
        .\Source\OutDir\x86\Release\UnitTest.exe -Run
    - name: Create NuGet package
      run: |
        cd .\Source
        nuget pack
    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        name: v${{steps.relver.outputs.relver}}
        tag_name: v${{steps.relver.outputs.relver}}
        body: "**NuGet Package**: https://www.nuget.org/packages/KNSoft.NDK/${{steps.relver.outputs.relver}}"
        prerelease: true
        preserve_order: true
        fail_on_unmatched_files: true
        generate_release_notes: true
        files: ./Source/KNSoft.NDK.${{steps.relver.outputs.relver}}.nupkg
